version: '3.3'

networks:
  default:
    ipam:
      config:
        - subnet: 172.50.0.0/16

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 5000:5000
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379



